title: Aaron Saray | Milwaukee Web Developer, PHP Programmer
url: http://www.aaronsaray.com
timezone: America/Chicago

markdown: kramdown
permalink: /:year/:title
exclude: [README.md, workflow-tools, .DS_Store, LICENSE]

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"
        - "/feed.xml"
        - "/Resume-Aaron_Saray.pdf"
        - "/css/main.css"
    include_posts:
        - "/blog.html"

sass:
    style: compressed
    
compress_html:
   clippings: all
