# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aaron Saray | Milwaukee Web Developer, PHP Programmer
url: http://www.aaronsaray.com

# Build settings
markdown: kramdown
permalink: /:year/:title
exclude: [README.md, build.sh, deploy.sh]

# sitemap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"
        - "/feed.xml"
        - "/Resume-Aaron_Saray.pdf"
        - "/css/main.css"
    include_posts:
        - "/blog.html"
